AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
    searchphotos:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: lambda_function.lambda_handler
        Runtime: python3.8
        CodeUri: .
        Description: ''
        MemorySize: 128
        Timeout: 3
        Role: 'arn:aws:iam::954518116297:role/service-role/search-photos-role-ozqvd58f'
        Events:
          Api1:
            Type: Api
            Properties:
              Path: /search
              Method: GET
          Api2:
            Type: Api
            Properties:
              Path: /MyResource
              Method: ANY
          Api3:
            Type: Api
            Properties:
              Path: /MyResource
              Method: ANY
              
    indexphotos:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: lambda_function.lambda_handler
        Runtime: python3.8
        CodeUri: .
        Description: ''
        MemorySize: 128
        Timeout: 3
        Role: 'arn:aws:iam::954518116297:role/service-role/index-photos-role-zwj21oe2'
        Events:
          BucketEvent1:
            Type: S3
            Properties:
              Bucket:
                Ref: Bucket1
              Events:
                - 's3:ObjectCreated:Put'
    Bucket1:
      Type: 'AWS::S3::Bucket'

